### ISSUE TITLE
Usage with phpcs pear package or standalone phpcs.phar

### ISSUE THREAD

**Issue by rohanvakharia** [object-calisthenics/phpcs-calisthenics-rules#67] opened 2017-06-21 12:35 UTC
I was trying to run calisthenics standard for pear package [PHPCS](https://pear.php.net/PHP_CodeSniffer) but it is not working.

What is the best way to use this with pear package or standalone phar file?

**Comment by rohanvakharia** [comment] 2017-06-21 13:59
[Usage is tested](https://github.com/object-calisthenics/phpcs-calisthenics-rules#usage) Is tested for phpcs composer package. In the composer case we just need to install phpcs using composer require.

what about global phpcs package?
In the global case,
- PHPCS installed via [pear channels ](https://pear.php.net/PHP_CodeSniffer)
- PHPCS installed via [phar package](https://github.com/squizlabs/PHP_CodeSniffer#installation)

**Comment by TomasVotruba** [comment] 2017-06-21 14:08
I'm not familliar with using phar or pear, since it doesn't support reliable versioning as comoser.

Could you add test for that into `.travis.yml` under [composer version test](https://github.com/object-calisthenics/phpcs-calisthenics-rules/blob/c541a84099de3670feb474dc73cd3d17a43d78fc/.travis.yml#L23)?

**Comment by rohanvakharia** [comment] 2017-06-21 14:26
Can you be able to guide on how do I use this standard with multiple projects without including in every project?

**Comment by TomasVotruba** [comment] 2017-06-21 15:11
What exactly do you mean?

**Comment by UFOMelkor** [comment] 2017-06-21 15:17
Is this what you are looking for? https://getcomposer.org/doc/03-cli.md#global

**Comment by rohanvakharia** [comment] 2017-06-21 16:49
This package is a custom standard for PHPCS. As per the documentation I need to require PHPCS and this package in every project to use the sniffs. If you have gone through the PHPCS composer package, I can use PHPCS in both ways global as well as local. So if I have phpcs installed globally, how can I install/ integrate this package / standard with PHPCS in a global way so that I don't have to add this package to all my project. I can directly use this standard from global installation?

**Comment by UFOMelkor** [comment] 2017-06-21 17:02
Run `composer global require object-calisthenics/phpcs-calisthenics-rules` and then
`$COMPOSER_HOME/vendor/bin/phpcs src tests -sp --standard=$COMPOSER_HOME/vendor/object-calisthenics/phpcs-calisthenics-rules/src/ObjectCalisthenics/ruleset.xml`
If `$COMPOSER_HOME` is not defined, please have a look at https://getcomposer.org/doc/03-cli.md#composer-home to find the composer home directory on your computer.

**Comment by rohanvakharia** [comment] 2017-06-23 11:59
I run the above command and received following error

```
PHP Fatal error:  Uncaught Error: Class 'Nette\Utils\Strings' not found in /home/rohan/.config/composer/vendor/object-calisthenics/phpcs-calisthenics-rules/src/ObjectCalisthenics/Helper/Naming.php:43
Stack trace:
#0 /home/rohan/.config/composer/vendor/object-calisthenics/phpcs-calisthenics-rules/src/ObjectCalisthenics/Sniffs/NamingConventions/ElementNameMinimalLengthSniff.php(40): ObjectCalisthenics\Helper\Naming::getElementName(Object(PHP_CodeSniffer\Files\LocalFile), 87)
#1 /usr/share/php/PHP/CodeSniffer/src/Files/File.php(431): ObjectCalisthenics\Sniffs\NamingConventions\ElementNameMinimalLengthSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 87)
#2 /usr/share/php/PHP/CodeSniffer/src/Files/LocalFile.php(94): PHP_CodeSniffer\Files\File->process()
#3 /usr/share/php/PHP/CodeSniffer/src/Runner.php(566): PHP_CodeSniffer\Files\LocalFile->process()
#4 /usr/share/php/PHP/CodeSniffer/src/Runner.php(383): PHP_CodeSniffer\Runner->processFile(Object(PHP_CodeSniffer\Files\LocalFile))
#5 /usr/share/php/PHP/CodeSniffer/src/Runner.php(112): PHP_CodeSniffer\R in /home/rohan/.config/composer/vendor/object-calisthenics/phpcs-calisthenics-rules/src/ObjectCalisthenics/Helper/Naming.php on line 43

```

As per the requirement I should have `Nette\Utils` package which was already installed via composer.

Here is the output of  `composer global show -i`
```
guzzlehttp/guzzle                            6.2.0  Guzzle is a PHP HTTP client library
guzzlehttp/promises                          1.1.0  Guzzle promises library
guzzlehttp/psr7                              1.3.0  PSR-7 message implementation
laravel/installer                            v1.3.3 Laravel application installer.
nette/utils                                  v2.4.6 Nette Utility Classes
object-calisthenics/phpcs-calisthenics-rules v3.0.1 PHP CodeSniffer Object Calisthenics rules/sniffs
psr/http-message                             1.0    Common interface for HTTP messages
squizlabs/php_codesniffer                    3.0.1  PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defined s...
symfony/console                              v3.0.6 Symfony Console Component
symfony/polyfill-mbstring                    v1.1.1 Symfony polyfill for the Mbstring extension
symfony/process                              v3.0.6 Symfony Process Component

```

How can I solve this?

**Comment by TomasVotruba** [comment] 2017-06-23 14:22
@rohanvakharia I've tried the same "composer global" setup and it works for me.
I also see `Nette\Utils` is already there in your report.

Not sure if bug in composer. Maybe ask in [composer issues](https://github.com/composer/composer/issues).

**Comment by rohanvakharia** [comment] 2017-06-24 16:28
Ubuntu 16.04

**Comment by UFOMelkor** [comment] 2017-06-24 19:02
Did you run `/home/rohan/.config/composer/vendor/bin/phpcs src tests -sp --standard=/home/rohan/.config/composer/vendor/object-calisthenics/phpcs-calisthenics-rules/src/ObjectCalisthenics/ruleset.xml`
or `vendor/bin/phpcs src tests -sp --standard=/home/rohan/.config/composer/vendor/object-calisthenics/phpcs-calisthenics-rules/src/ObjectCalisthenics/ruleset.xml`
?

**Comment by rohanvakharia** [comment] 2017-06-26 03:44
/home/rohan/.config/composer/vendor/bin/phpcs src tests -sp --standard=/home/rohan/.config/composer/vendor/object-calisthenics/phpcs-calisthenics-rules/src/ObjectCalisthenics/ruleset.xml

**Comment by TomasVotruba** [comment] 2017-06-26 07:02
Btw, I'd recommend using `composer create-project ...` approach, that will install project to standalone directory. There you have dependencies under control and you can use it in multiple other projects.

`composer global ...` is more different to use

**Comment by TomasVotruba** [comment] 2017-07-06 16:21
What's state is this in?

**Comment by rohanvakharia** [comment] 2017-07-06 16:41
I have multiple projects where I need to run these rules.
I tried different approaches to run it but couldn't succeed except adding in the project composer file.

I have installed a PHPCS standalone(phar file) in my bin folder. That gives me an easy access anywhere from terminal and in sublime as well using linter.

The way you are telling me to use that, I will need to add the package in each and every project which is not possible for me.

**Comment by TomasVotruba** [comment] 2017-07-06 17:12
> The way you are telling me to use that, I will need to add the package in each and every project...

I will try install it step by step.

## FAIL :cry: 

### 1. Install It

```bash
# composer create-project <package-name> <destination-directory>
composer create-project object-calisthenics/phpcs-calisthenics-rules object-calisthenics-rules 
```

Now this package is located in `/object-calisthenics-rules` directory.

`ruleset.xml` is located in:

```bash
object-calisthenics-rules/src/ObjectCalisthenics/ruleset.xml
```

### 2. Run It with Own phar/bin

```bash
php_codesniffer/bin/phpcs standalone-directory/src -sp --standard=standalone-directory/src/ObjectCalisthenics/ruleset.xml
```

That fails with exception the same "Nette\Utils\Strings" exception: 

![image](https://user-images.githubusercontent.com/924196/27923304-3c5c77d0-627e-11e7-9627-abc2e63869ee.png)

---

This is caused by using extra classes that `phpcs` is unable to load.
That's why composer is needed at least at some way.

## SOLUTION :flag:

When you use `vendor/bin/phpcs` that is in the same directory:

```bash
standalone-directory/vendor/bin/phpcs standalone-directory/src -sp --standard=standalone-directory/src/ObjectCalisthenics/ruleset.xml
```

All works fine:

![image](https://user-images.githubusercontent.com/924196/27923453-af1dc2ba-627e-11e7-927a-0e3c7be21b44.png)


And you can analyze any directory you need:

```bash
standalone-directory/vendor/bin/phpcs other-project -sp --standard=standalone-directory/src/ObjectCalisthenics/ruleset.xml
```

![image](https://user-images.githubusercontent.com/924196/27923510-e6e3e436-627e-11e7-89c9-dfe90c4077f1.png)


Can you try that?

**Comment by rohanvakharia** [comment] 2017-07-06 17:36
Thank you for detailed solution.

It is a very good work around for my problem.

I have tried this solution where I need to install PHPCS package using composer in a standalone directory followed by object calisthenics package which will install a `Nette\Utils` package as a dependecy.

Solution accepted.

Just a concern:
I was going through the code and found that you haven't used `Nette\Utils` package that extensively.
Can't you remove the dependency from your package which will make your package work for the failing use case which you explained to me?

**Comment by rohanvakharia** [comment] 2017-07-06 17:37
I can send you a PR if you don't mind.

**Comment by TomasVotruba** [comment] 2017-07-06 17:39
> Solution accepted.

:+1: 

> Can't you remove the dependency from your package which will make your package work for the failing use case which you explained to me?

I though about this but though there are more external dependencies, that would have to be taken care of. 
You can try that and if it works send PR. + We'll have to add a note about this to README for future generations to be careful, because adding dependencies is quite common.

> I can send you a PR if you don't mind.

Sure, that would be great! :clap:

**Comment by TomasVotruba** [comment] 2017-07-08 10:04
Do you have an idea when do you get to this?

**Comment by rohanvakharia** [comment] 2017-07-09 02:23
It won't take more than couple of days as I am working on client's project, will update you once it's done.

**Comment by TomasVotruba** [comment] 2017-07-09 13:26
Thanks for the info.

**Comment by TomasVotruba** [comment] 2017-07-31 14:47
Closing for time out. Feel free to reopen with PR.

**Closed** 2017-07-31 14:47 UTC
